import '@/styles/globals.css'
import Image from 'next/image'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js'
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en'>
			<body>
				<div className='fixed -z-10 h-screen w-screen'>
					<Image
						src={'/stacked-waves-haikei.svg'}
						fill
						quality={100}
						alt='flatbg'
						className='object-cover brightness-[.75]'
					/>
				</div>
				{children}
			</body>
		</html>
	)
}
