import { getServerSession } from "next-auth";
import type { Metadata } from "next";
import { authOptions } from "@/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: { shortcut: "/favicon.ico" },
};

export default async function Home() {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
      <pre>{JSON.stringify(session)}</pre>
    </>
  );
}
